
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('items').del()
    .then(function () {
      // Inserts seed entries
      return knex('items').insert([
        {item_id: 12003, item_name: 'Lawnmower', category: 'Tools', description: 'This is a Self Propelled Lawnmower, makes chores much easier, about 4 years old, still in nice condition, all you need is to pay for your own petrol.', location: 'Karori', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381181/mower_vlcqxf.jpg', owner_id: 7005, available: true},
        {item_id: 12004, item_name: 'Kayak', category: 'Sport and Recreation', description: 'Comes with paddle and has storage area for bait and snacks if you decide to go fishing.', location: 'Kapiti', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381333/kayak_eyxe3r.jpg', owner_id: 7006, available: true},
        {item_id: 12005, item_name: 'Hovercraft', category: 'Other', description: 'Home made, single seat, super speedy and can travel over land, water, mud, ice, and other surfaces.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381486/hovercraft_qsuldd.jpg', owner_id: 7007, available: true},
        {item_id: 12006, item_name: 'Guitar', category: 'Musical Instruments', description: 'Childs size electric guitar, great to teach your child how to play and comes with a tuner to make sure its always in tune.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381578/guitar_lox9qk.png', owner_id: 7008, available: true},
        {item_id: 12007, item_name: 'Hedge Trimmer', category: 'Tools', description: 'Petrol hedge trimmer, makes gardening more enjoyable and faster.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381742/hedge-trimmer_imkmln.jpg', owner_id: 7009, available: true},
        {item_id: 12008, item_name: 'BMX Bike', category: 'Sport and Recreation', description: 'Enjoy yourself with my awesome BMX bike, it will let you perform some sweet tricks and help you impress your friends and show off in fornt of your crush.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492381947/bmx_i6zpaa.jpg', owner_id: 7010, available: true},
        {item_id: 12009, item_name: 'Small Trailer', category: 'Other', description: 'You car not big enough for the job? Then here is the perfect trailer for you, whether your moving, dumping rubbish or other things.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492382152/trailer_ogfcrk.jpg', owner_id: 7011, available: true},
        {item_id: 12010, item_name: 'MixMaster 5000', category: 'Musical Instruments', description: 'Need to spin some phat beats for your next party? The twin turntables on the MixMaster 5000 will allow you to DJ like a pro and get the party cranking!', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492382264/djdeck_mqtcow.jpg', owner_id: 7012, available: true},
        {item_id: 12011, item_name: 'Tree Cutter 4 Chainsaw', category: 'Tools', description: 'Petrol Powered with sharp teeth, will allow you to cut down unwated and annoying trees in the way.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492382497/chainsaw_ac2k1j.jpg', owner_id: 7013, available: true},
        {item_id: 12012, item_name: 'Sky Buzzer Drone', category: 'Other', description: 'Always wondered what the world looked like from a birds view? Well you can finally know with this 4 blades drone that has a 40 minute battery life plus an inbuilt HD camera that takes 1920x1080 video', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492382710/drone_hscbun.jpg', owner_id: 7014, available: true},
        {item_id: 12013, item_name: 'Drum Kit', category: 'Musical Instruments', description: 'Perfect for an old band reunion and to maybe tutor someone how to play the drums, they have just recently been tuned and repaired, they also come with a stool.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492386697/drumkit_mrf2yj.jpg', owner_id: 7005, available: true},
        {item_id: 12014, item_name: 'Spade', category: 'Tools', description: 'Great for digging holes and tidyng up your garden!.', location: 'Wellington', image_url: 'http://res.cloudinary.com/hpyyiawap/image/upload/v1492388328/spade_iqkmf9.jpg', owner_id: 7009, available: true}
      ])
    })
}
